# Generated by Django 4.0.6 on 2022-08-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('identifier', models.CharField(max_length=50)),
                ('name_client', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('in_wait', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prestamo de producto',
                'verbose_name_plural': 'Detalles de prestamo de producto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProducLoanDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('quantity', models.IntegerField()),
                ('code_list', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productloan')),
            ],
            options={
                'verbose_name': 'Detalle de prestamo',
                'verbose_name_plural': 'Detalles de prestamo',
                'ordering': ['id'],
            },
        ),
    ]
