# Generated by Django 4.0.6 on 2022-08-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productloan_producloandetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducLoanDetail',
            new_name='ProductLoanDetail',
        ),
        migrations.AlterModelOptions(
            name='productloan',
            options={'ordering': ['-id'], 'verbose_name': 'Prestamo de producto', 'verbose_name_plural': 'Prestamos de producto'},
        ),
    ]
